import Image from 'next/image'
import { useRouter } from 'next/router'

import Layout from '../components/layout/layout'
import Head from 'next/head'
import Hero from '../components/hero'
import AboutMe from './#about'
import Projects from './#projects'

import styles from '../styles/Home.module.scss'
import { useEffect, useState } from 'react'
import { PlaylistsContextConsumer } from '../components/playlistsContext'
import { getAllData } from '../components/playlists/CRUD'

export default function Home() {
    const { toPlaylists } = PlaylistsContextConsumer()
    const router = useRouter()

    console.log(toPlaylists)

    useEffect(() => {
        if (toPlaylists) {
            router.push('/playlists')
        }
    }, [toPlaylists])

    return (
        <>
            <Head>
                <title>Maveryck Maya</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles['page--container']} id="page--container">
                <Hero />
            </div>
        </>
    )
}
