import Image from 'next/image'

import Layout from '../components/layout/layout'
import Head from 'next/head'
import Hero from '../components/hero'
import AboutMe from './#about'
import Projects from './#projects'

import styles from '../styles/Home.module.scss'
import { useEffect } from 'react'

export default function Home() {
    return (
        <>
            <Head>
                <title>Maveryck Maya</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles['page--container']} id="page--container">
                <Hero />
            </div>
        </>
    )
}
